apiVersion: v1
kind: ConfigMap
metadata:
  name: kafbat-config
  namespace: default
data:
  config.yml: |
    kafka:
      clusters:
        - name: local-kafka
          bootstrapServers: kafka.default.svc.cluster.local:9092
    auth:
      type: disabled
    management:
      health:
        ldap:
          enabled: false