apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafbat-config
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/tim-str/helm-infra.git
    targetRevision: HEAD
    path: charts/kafbat
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true