apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafbat
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://ui.charts.kafbat.io
    chart: kafka-ui
    targetRevision: 1.x.x
    helm:
      values: |
        yamlApplicationConfig:
          kafka:
            clusters:
              - name: local-kafka
                bootstrapServers: kafka.default.svc.cluster.local:9092
          auth:
            type: disabled
          management:
            health:
              ldap:
                enabled: false
        resources:
          requests:
            cpu: 50m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true