apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  labels:
    app: localstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
        - name: localstack
          image: localstack/localstack:3.8
          ports:
            - containerPort: 4566
          env:
            - name: SERVICES
              value: "s3,sqs,sns,dynamodb,secretsmanager,iam,msk"
            - name: DATA_DIR
              value: /var/lib/localstack/data
            - name: PERSISTENCE
              value: "1"
          volumeMounts:
            - name: localstack-data
              mountPath: /var/lib/localstack/data
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
      volumes:
        - name: localstack-data
          persistentVolumeClaim:
            claimName: localstack-pvc