apiVersion: v1
kind: PersistentVolume
metadata:
  name: localstack-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistenceVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /tmp/localstack-data