apiVersion: v1
kind: Service
metadata:
  name: localstack
  labels:
    app: localstack
spec:
  selector:
    app: localstack
  ports:
    - name: gateway
      port: 4566
      targetPort: 4566
  type: ClusterIP